/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SampleChildComponent {
        "childName": string;
    }
    interface SampleComponent {
        "bestDrummer": string;
        "updateStatement": () => Promise<void>;
    }
}
declare global {
    interface HTMLSampleChildComponentElement extends Components.SampleChildComponent, HTMLStencilElement {
    }
    var HTMLSampleChildComponentElement: {
        prototype: HTMLSampleChildComponentElement;
        new (): HTMLSampleChildComponentElement;
    };
    interface HTMLSampleComponentElement extends Components.SampleComponent, HTMLStencilElement {
    }
    var HTMLSampleComponentElement: {
        prototype: HTMLSampleComponentElement;
        new (): HTMLSampleComponentElement;
    };
    interface HTMLElementTagNameMap {
        "sample-child-component": HTMLSampleChildComponentElement;
        "sample-component": HTMLSampleComponentElement;
    }
}
declare namespace LocalJSX {
    interface SampleChildComponent {
        "childName"?: string;
    }
    interface SampleComponent {
        "bestDrummer"?: string;
    }
    interface IntrinsicElements {
        "sample-child-component": SampleChildComponent;
        "sample-component": SampleComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sample-child-component": LocalJSX.SampleChildComponent & JSXBase.HTMLAttributes<HTMLSampleChildComponentElement>;
            "sample-component": LocalJSX.SampleComponent & JSXBase.HTMLAttributes<HTMLSampleComponentElement>;
        }
    }
}
